In [53]:
import pandas as pd
import seaborn as sns

In [54]:
characters_df = pd.read_csv('marvel-characters/characters.csv')
characters2comics_df = pd.read_csv('marvel-characters/charactersToComics.csv')
characters_stats_df = pd.read_csv('marvel-characters/characters_stats.csv')
characters_info_df = pd.read_csv('marvel-characters/marvel_characters_info.csv')
superpowers_df = pd.read_csv('marvel-characters/superheroes_power_matrix.csv')
# other_info_df = pd.read_csv('marvel-characters/marvel_dc_characters.csv')

In [55]:
characters_df.head(3)

   characterID             name
0      1009220  Captain America
1      1010740   Winter Soldier
2      1009471        Nick Fury

In [56]:
characters_stats_df.head(3)

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
0,3-D Man,good,50,31,43,32,25,52,233
1,A-Bomb,good,38,100,17,80,17,64,316
2,Abe Sapien,good,88,14,35,42,35,85,299

In [57]:
characters_info_df.head(3)

,ID,Name,Alignment,Gender,EyeColor,Race,HairColor,Publisher,SkinColor,Height,Weight
0,0,A-Bomb,good,Male,yellow,Human,No Hair,Marvel Comics,-,203.0,441.0
1,1,Abe Sapien,good,Male,blue,Icthyo Sapien,No Hair,Dark Horse Comics,blue,191.0,65.0
2,2,Abin Sur,good,Male,blue,Ungaran,No Hair,DC Comics,red,185.0,90.0

In [58]:
superpowers_df.head(3)

,Name,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [59]:
agg_df = pd.merge(
    pd.merge(
        pd.merge(
            characters_df, characters_stats_df, left_on='name', right_on='Name', how='inner'
        ), 
        characters_info_df, on='Name', how='inner'
    ), 
    superpowers_df, on='Name', how='inner'
)

In [60]:
agg_df.drop(columns=[
    'name', 'Alignment_y', 'Durability_y', 'Intelligence_y', 'ID'
], axis=1, inplace=True)
agg_df.rename({
    'Alignment_x': 'Alignment', 
    'Durability_x': 'Durability', 
    'Intelligence_x': 'Intelligence'
}, axis=1, inplace=True)

In [62]:
agg_df.shape

(187, 183)

In [64]:
agg_df.to_csv('marvel_characters_aggregated.csv', index=False)