In [4]:
load('../datasets/ICPSR_21600/DS0010/21600-0010-Data.rda')

In [5]:
ls()

[1] "da21600.0010"

In [9]:
View(da21600.0010)

       AID      RRELNO RPREGNO H3TP1
1      57100270  1     1       (4) (4) Live birth
2      57101310  1     1       (4) (4) Live birth
3      57101310  1     2       (4) (4) Live birth
4      57117542 18     1       (1) (1) Miscarriage
5      57118381  5     1       (5) (5) Pregnancy not yet ended
6      57120005  4     1       (1) (1) Miscarriage
7      57120046  1     1       (4) (4) Live birth
8      57120371  1     1       (1) (1) Miscarriage
9      57120371  1     2       (3) (3) Single, stillbirth
10     57134970  1     1       (3) (3) Single, stillbirth
11     57134970  1     2       (5) (5) Pregnancy not yet ended
12     57135078  1     1       (5) (5) Pregnancy not yet ended
13     57135078  1     2       (4) (4) Live birth
14     57135078  1     3       (4) (4) Live birth
15     57135078  4     1       (4) (4) Live birth
16     57135078  5     1       (5) (5) Pregnancy not yet ended
17     57135078  7     1       (4) (4) Live birth
18     57136630  7     1       (2) (2) Abortion
19     57154249  2     1       (4) (4) Live birth
20     57154249  2     2       (2) (2) Abortion
21     57154249  2     3       (4) (4) Live birth
22     57154249  2     4       (1) (1) Miscarriage
23     57154779  1     1       (4) (4) Live birth
24     57154779  1     2       (4) (4) Live birth
25     57157723  1     1       (4) (4) Live birth
26     57160648  4     1       (4) (4) Live birth
27     57164981  1     1       (5) (5) Pregnancy not yet ended
28     57165081  1     1       (4) (4) Live birth
29     57165081  1     2       (3) (3) Single, stillbirth
30     57178110  1     1       (4) (4) Live birth
<U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE>
2319   99714927 1      1       (2) (2) Abortion
2320   99714927 6      1       (2) (2) Abortion
2321   99714942 2      1       (4) (4) Live birth
2322   99715251 1      1       (4) (4) Live birth
2323   99715365 2      1       (1) (1) Miscarriage
2324   99715365 3      1       (1) (1) Miscarriage
2325   99715932 3      1       (4) (4) Live birth
2326   99715934 1      1       (5) (5) Pregnancy not yet ended
2327   99715954 1      1       (4) (4) Live birth
2328   99715954 1      2       (4) (4) Live birth
2329   99715954 1      3       (2) (2) Abortion
2330   99716258 1      1       (2) (2) Abortion
2331   99716396 1      1       (2) (2) Abortion
2332   99716396 2      1       (2) (2) Abortion
2333   99716396 2      2       (2) (2) Abortion
2334   99716396 3      1       (4) (4) Live birth
2335   99716396 3      2       (4) (4) Live birth
2336   99716892 2      1       (2) (2) Abortion
2337   99716892 3      1       (4) (4) Live birth
2338   99716892 3      2       (5) (5) Pregnancy not yet ended
2339   99716979 2      1       (2) (2) Abortion
2340   99717365 1      1       (4) (4) Live birth
2341   99717911 1      1       (4) (4) Live birth
2342   99718016 2      1       (4) (4) Live birth
2343   99718041 1      1       (2) (2) Abortion
2344   99718088 1      1       (4) (4) Live birth
2345   99718104 7      1       (4) (4) Live birth
2346   99718305 1      1       (4) (4) Live birth
2347   99718305 1      2       (4) (4) Live birth
2348   99718925 1      1       (4) (4) Live birth
       H3TP2M             H3TP2Y H3TP3
1      (04) (4) April     1997   NA
2      (03) (3) March     1996   (1) (1) 1 live birth
3      (03) (3) March     1997   (1) (1) 1 live birth
4      (09) (9) September 2001   NA
5      (01) (1) January   2002   NA
6      (08) (8) August    1999   NA
7      (12) (12) December 1999   (1) (1) 1 live birth
8      (10) (10) October  2000   NA
9      (04) (4) April     2001   NA
10     (09) (9) September 1998   NA
11     (02) (2) February  2002   NA
12     (02) (2) February  2001   NA
13     (01) (1) January   1996   (1) (1) 1 live birth
14     (01) (1) January   2001   NA
15     (01) (1) January   1996   (1) (1) 1 live birth
16     (02) (2) February  2002   NA
17     (01) (1) January   2001   (1) (1) 1 live birth
18     (08) (8) August    2000   NA
19     (10) (10) October  1995   (1) (1) 1 live birth
20     (08) (8) August    1996   NA
21     (01) (1) January   1999   (1) (1) 1 live birth
22     (01) (1) January   2000   NA
23     (11) (11) November 1999   (1) (1) 1 live birth
24     (01) (1) January   2001   (2) (2) 2 live births
25     (08) (8) August    2001   (1) (1) 1 live birth
26     (05) (5) May       1999   (1) (1) 1 live birth
27     (05) (5) May       2002   NA
28     (12) (12) December 2000   (1) (1) 1 live birth
29     (11) (11) November 2000   NA
30     (04) (4) April     2001   (1) (1) 1 live birth
<U+22EE> <U+22EE>           <U+22EE> <U+22EE>
2319   (03) (3) March     1996   NA
2320   (11) (11) November 1998   NA
2321   (03) (3) March     2000   (1) (1) 1 live birth
2322   (12) (12) December 1997   (1) (1) 1 live birth
2323   (05) (5) May       2000   NA
2324   (04) (4) April     2001   NA
2325   (04) (4) April     2000   (1) (1) 1 live birth
2326   (07) (7) July      2002   NA
2327   (05) (5) May       2001   (1) (1) 1 live birth
2328   (05) (5) May       2001   (1) (1) 1 live birth
2329   (02) (2) February  1998   NA
2330   (10) (10) October  1999   NA
2331   (09) (9) September 1998   NA
2332   (08) (8) August      NA   NA
2333   (06) (6) June      1999   NA
2334   (12) (12) December 2000   (1) (1) 1 live birth
2335   (10) (10) October  2001   (1) (1) 1 live birth
2336   (03) (3) March     1998   NA
2337   (06) (6) June      1999   (1) (1) 1 live birth
2338   (07) (7) July      2002   NA
2339   (04) (4) April     1999   NA
2340   (02) (2) February  1999   (1) (1) 1 live birth
2341   (04) (4) April     2000   (1) (1) 1 live birth
2342   (02) (2) February  1997   (1) (1) 1 live birth
2343   (11) (11) November 1996   NA
2344   (11) (11) November 2001   (1) (1) 1 live birth
2345   (03) (3) March     2000   (1) (1) 1 live birth
2346   (05) (5) May       2001   (1) (1) 1 live birth
2347   (07) (7) July      1999   (1) (1) 1 live birth
2348   (01) (1) January   2001   (1) (1) 1 live birth